spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/devplatform?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: 582373
  redis:
     host: 127.0.0.1
     port: 6379
  mail:
     host: smtp.qq.com
     username: 582373673@qq.com
     password: hmglrpusqtdubcca
     properties.smtp.auth: true
     properties.smtp.timeout: 2500
     properties.mail.smtp.ssl.enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  resources:
    static-locations: file:D://devplatform_files


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
server:
  port: 8080
